package virtus.synergy.design_system.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6638E4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE7DEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1F005F)
val md_theme_light_secondary = Color(0xFF314DDF)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF000F5C)
val md_theme_light_tertiary = Color(0xFF006C52)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF5CFCCA)
val md_theme_light_onTertiaryContainer = Color(0xFF002117)
val md_theme_light_error = Color(0xFFB72020)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFFCCBDFF)
val md_theme_light_surfaceTint = Color(0xFF6638E4)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF8FAFA)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)

val md_theme_dark_primary = Color(0xFFCCBDFF)
val md_theme_dark_onPrimary = Color(0xFF360096)
val md_theme_dark_primaryContainer = Color(0xFF5B516F)
val md_theme_dark_onPrimaryContainer = Color(0xFFE7DEFF)
val md_theme_dark_secondary = Color(0xFFBBC3FF)
val md_theme_dark_onSecondary = Color(0xFF001E91)
val md_theme_dark_secondaryContainer = Color(0xFF062FC8)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_tertiary = Color(0xFF34DFAF)
val md_theme_dark_onTertiary = Color(0xFF003829)
val md_theme_dark_tertiaryContainer = Color(0xFF00513D)
val md_theme_dark_onTertiaryContainer = Color(0xFF5CFCCA)
val md_theme_dark_error = Color(0xFFFFB4AC)
val md_theme_dark_errorContainer = Color(0xFF93000D)
val md_theme_dark_onError = Color(0xFF690006)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inversePrimary = Color(0xFF6638E4)
val md_theme_dark_surfaceTint = Color(0xFFCCBDFF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF101415)
val md_theme_dark_onSurface = Color(0xFFC4C7C7)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)


val seed = Color(0xFF6638E4)
