name: Mind Tempus quick release
run-name: ${{ github.actor }} is preparing a new release 🚀
on:
  workflow_dispatch:
jobs:
  GitHub-Actions:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Increment version code
        run: |
          sed -i '' 's/val appVersionCode by extra { [0-9]* }/val appVersionCode by extra { ${{ github.run_number }} }/' /Users/runner/work/Mind-Tempus/Mind-Tempus/app_version_code.gradle.kts

      - name: Commit and push version code increment
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.G_TOKEN }}@github.com/${{ github.repository }}
          git add app_version_code.gradle.kts
          git commit -m "Increment version code"
          git push origin ${{ github.ref }}

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        run:
          echo $ENCODED_STRING | base64 -d > $SIGNING_KEY_STORE_PATH

      - name: Decode Key Store Data
        env:
          KEY_STORE_DATA: ${{ secrets.KEY_STORE_DATA }}
        run:
          echo $KEY_STORE_DATA | base64 -d > /Users/runner/work/Mind-Tempus/Mind-Tempus/key.properties

      - name: Decode Google Service File
        env:
          GOOGLE_SERVICE_ENCODED_STRING: ${{ secrets.GOOGLE_SERVICE_ENCODED_STRING }}
          GOOGLE_SERVICE_FILE_PATH: ${{ secrets.GOOGLE_SERVICE_FILE_PATH }}
        run:
          echo $GOOGLE_SERVICE_ENCODED_STRING | base64 -d >  $GOOGLE_SERVICE_FILE_PATH

      - name: Build Release bundle
        run: ./gradlew bundleRelease

      - name: Decode Google Service File
        env:
          KEY_STORE_DATA: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run:
          echo $KEY_STORE_DATA | base64 -d > /Users/runner/work/Mind-Tempus/Mind-Tempus/app/mind-tempus.json

      - name: Publish to Google play store
        run: ./gradlew publishBundle

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files:
            app/build/outputs/bundle/release/app-release.aab
