name: Mind Tempus quick release
run-name: ${{ github.actor }} is preparin a new release 🚀
on:
  workflow_call:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          with:
            java-version: '17'
            distribution: 'temurin'
      # You may pin to the exact commit or the version.
      # uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407
      - uses: r0adkll/sign-android-release@v1
        with:
          # The directory to find your release to sign
          releaseDirectory: ${{ github.workspace}} /app/build/outputs/apk/release/app-release.apk
          signingKeyBase64: ${{secrets.APP_KEY_STORE}}
          alias: ${{secrets.ALIAS}}
          keyStorePassword: ${{secrets.USER_CODE}}
          keyPassword: ${{secrets.ALIAS_CODE}}
