name: Mind Tempus quick release
run-name: ${{ github.actor }} is preparing a new release 🚀
on:
  workflow_dispatch:
jobs:
  GitHub-Actions:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        run:
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

      - name: Decode Google Service File
        env:
          GOOGLE_SERVICE_ENCODED_STRING: ${{ secrets.GOOGLE_SERVICE_ENCODED_STRING }}
          GOOGLE_SERVICE_FILE_PATH: ${{ secrets.GOOGLE_SERVICE_FILE_PATH }}
        run:
          echo $GOOGLE_SERVICE_ENCODED_STRING | base64 -d >  $GOOGLE_SERVICE_FILE_PATH

      - name: Increment version code
        run: |
          current_version=$(awk '/val appVersionCode by extra/ {print $NF}' app_version_code.gradle.kts | tr -d '{}')
          new_version=$((current_version + 1))
          sed -i '' "s/val appVersionCode by extra { $current_version }/val appVersionCode by extra { $new_version }/" app_version_code.gradle.kts

      - name: Commit and push version code increment
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run:
          set -x
          git config --global user.name '${{ github.actor }}'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app_version_code.gradle.kts
          git commit -m 'Increment version code'
          git push origin ${{ github.ref }}

      - name: Build Release bundle
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ALIAS_CODE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.USER_CODE }}
        run: ./gradlew bundleRelease

      - name: Publish to Google play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: virtus.synergy.mindtempus
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files:
            app/build/outputs/bundle/release/app-release.aab
